### ISSUE TITLE
[1.12] Server Crash caused by NoClassDefFound

### ISSUE THREAD

**Issue by Morpheus1101** [PrinceOfAmber/ForgeCreeperHeal#2]
Crash log @ https://puu.sh/wKCF8/3f54a6bec6.txt

Forge: *.2413
Mod Vers: 1.3.0

**Comment by PrinceOfAmber** [comment]
Working on a fix now, will be out in a few hours.

**Comment by Lothrazar** [comment]
Try out this new version https://minecraft.curseforge.com/projects/forge-creeper-heal-unofficial/files/2452839

**Comment by Morpheus1101** [comment]
Testing Now....

**Comment by Morpheus1101** [comment]
Everything seems to work as intended
