### ISSUE TITLE
SpongeForge Compatibility

### ISSUE THREAD

**Issue by tgstyle** [PrinceOfAmber/ForgeCreeperHeal#3]
Is there any reason why the 1.12 version is not working with SpongeForge? Previous versions on the official version worked fine (1.10.2).

**Comment by Lothrazar** [comment]
I'm not sure.  ive never used sponge.  When i start up a plain forge server it runs fine

**Comment by JBYoshi** [comment]
This should be fixed when https://github.com/SpongePowered/SpongeForge/pull/1911 is merged.
